download/urls.py
from django.conf.urls import url
from download.views import (initial_view, 
							order_view,
							photos_view,)


urlpatterns = [
    url(r'^$', initial_view, name='initial'),
    url(r'^order/$', order_view, name='order'),
    url(r'^photos/$', photos_view, name='photos'),

]

home/urls.py
from django.conf.urls import url
from home.views import home_view

urlpatterns = [
    url(r'^$', home_view, name='home_view'),

]

picpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^download/', include('download.urls', namespace='download')),
    url(r'^excursion/', include('excursion.urls', namespace='excursion')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

download/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import FileExtensionValidator

from django.db.models.signals import post_delete
from django.dispatch import receiver


class Pic(models.Model):
	date = models.DateField()
	image = models.ImageField(upload_to='pictures', 
							validators=[FileExtensionValidator(['jpg'])])
	verification_code = models.CharField(max_length=5)
	is_free = models.BooleanField(default=False)

@receiver(post_delete, sender=Pic) #Eliminar archivos de media
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 



class Downloader(models.Model):
	date = models.DateField(auto_now_add=True)
	name = models.CharField(max_length=100)
	lastname = models.CharField(max_length=100)
	email = models.EmailField(max_length=100)
	comment = models.TextField()

download/forms.py
from django import forms
from download.models import *

class DownloadPicForm(forms.Form):
	name = forms.CharField(
		label = 'Name', 
		max_length=200,
		widget=forms.TextInput(attrs={
			'class':'form-control cls-input',
			'placeholder': 'Name...'})
		)

	lastname = forms.CharField(
		label = 'Last Name', 
		max_length=200,
		widget=forms.TextInput(attrs={
			'class':'form-control cls-input',
			'placeholder': 'Last Name...'})
		)

	email = forms.EmailField(
		widget=forms.TextInput(attrs={
			'class':'form-control cls-input',
			'placeholder': 'email@domain.com'}))

	comment = forms.CharField(
		label = 'Comments', 
		max_length=300,
		widget=forms.Textarea(attrs={
			'rows':3, 'style':'resize:none',
			'class':'form-control cls-input',
			'placeholder': 'Enter your comment...'})
		)

	photo_date = forms.DateField(widget=forms.TextInput(attrs={
			'class':'form-control cls-input',
			'readonly':True
			
			}
		)
	)

	code = forms.CharField(
		label = "Day Code", 
		max_length=5,
		widget=forms.TextInput(attrs={
			'class':'form-control cls-input-code',
			'placeholder': '5 digits code'})
		)
	# def __init__(self, *args, **kwargs):
	# 	super(DownloadPicForm, self).__init__(*args, **kwargs)
	# 	for visible in self.visible_fields():
	# 		visible.field.widget.attrs['class'] = 'form-control cls-input'
	

	def clean_code(self):
		code_inserted = self.cleaned_data['code']  
		verification_code = Pic.objects.filter(date=self.cleaned_data['photo_date'])\
										.values_list('verification_code', flat=True)\
										.distinct()[0]

		if code_inserted != verification_code:
			raise forms.ValidationError("Invalid code! The code entered and code of this day doesn't match")
		return code_inserted

download/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json, zipfile, os
import ntpath
from datetime import datetime

from django.conf import settings
from wsgiref.util import FileWrapper
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from download.forms import DownloadPicForm
from download.models import Pic, Downloader

from PIL import Image

from paypal.standard.forms import PayPalPaymentsForm



def marked(absolute_path, name_img):
	watermark_img_path = '{}/images/personal/snippets/marcadeagua.png'.format(settings.STATICFILES_DIRS[0])
	base_image = Image.open(absolute_path)
	watermark = Image.open(watermark_img_path)
	width, height = base_image.size
	pos_X_mark, pos_Y_mark = int(0), int(height/2)
	# pos_X_mark, pos_Y_mark = int(width/4), int(height/4)


	transparent = Image.new('RGB', (width, height), (0,0,0))
	transparent.paste(base_image, (0,0))
	transparent.paste(watermark, (pos_X_mark, pos_Y_mark), mask=watermark)
	path_img_marked = '{}/marked/{}'.format(settings.MEDIA_ROOT, name_img)
	transparent.save(path_img_marked)
	return path_img_marked


def initial_view(request):
	"""
	If request is POST: 
		A form is returned with the photo_date as Initial Value
	If request is GET: 
		A query is made to DB to get Availables Dates and set it in Calendar
	"""
	if request.method == "POST":
		photo_date = request.POST.get('daterange')
		download_form = DownloadPicForm(initial={'photo_date':photo_date})
		context = {'download_form':download_form,
					'photo_date':photo_date
					}
		return render(request, 'order.html', context)


	else:
		available_dates = []

		queryset_dates = Pic.objects.all()\
							.values_list('date',flat=True).order_by('date')\
							.distinct()

		try:
			start = queryset_dates[0].strftime("%d-%m-%Y")
			end = queryset_dates.reverse()[0].strftime("%d-%m-%Y")
		except Exception as e:
			start=None
			end=None
		

		for f in queryset_dates:
			available_dates.append(str(f))
		available_dates = json.dumps(available_dates)


		contexto = {'available_dates':available_dates,
					'start': start,
					'end':end,
					}

		return render(request, "initial.html", contexto)


def order_view(request):
	"""
	If request is POST: 
		The form is validated, storage the Downloader and pass photo path and is_free attr.
	If request is GET: 
		redirect to initial template
	"""
	if request.method == "POST":
		form = DownloadPicForm(request.POST)
		if form.is_valid():
			data = form.cleaned_data
			downloader = Downloader(date=data['photo_date'],
									name=data['name'],
									lastname=data['lastname'],
									email=data['email'],
									comment=data['comment']
									)
			downloader.save()

			photos = Pic.objects.filter(date=data['photo_date'])\
								.values('image', 'is_free')

			context = {'photo_date':data['photo_date'],
						'photos': photos
						}

			request.session['lastname'] = data['lastname'] #almaceno el apellido en cache


			return render(request, 'photos.html', context)
			

		else:
			context = {'download_form':form,
						'photo_date': request.POST['photo_date']}
			return render(request, 'order.html', context)

	else:
		return redirect('/')


@csrf_exempt
def photos_view(request):
	"""
	If request is POST: 
		If is free download, download the photos with markwater
		If is full download, redirect to PayPal
	If request is GET:
		redirect to initial template
	"""
	if request.method == 'POST':
		if 'free' in request.POST.keys(): #Presiono el boton de descarga gratis
			with zipfile.ZipFile('MyTailorToursPhotos.zip', 'w') as export_zip:
				for key, value in request.POST.items():
					if key != 'free': #obvia name del boton
						path , is_free = key.split('_indicador_')
						img_path="{}/{}".format(settings.MEDIA_ROOT,path)

						if int(is_free):
							export_zip.write(img_path, os.path.basename(img_path))
						else:
							img_marked = marked(absolute_path=img_path, name_img=ntpath.basename(path))
							export_zip.write(img_marked, os.path.basename(img_marked))


			wrapper = FileWrapper(open('MyTailorToursPhotos.zip', 'rb'))
			content_type = 'application/zip'
			content_disposition = 'attachment; filename=MyTailorToursPhotos.zip'
			response = HttpResponse(wrapper, content_type=content_type)
			response['Content-Disposition'] = content_disposition

			#antes de retornar el .zip borro todas las fotos almacenadas
			#en el directorio /media/marked/ ya que las imagenes guardadas 
			#en esta carpeta son temporales

			folder_temp = '{}/marked'.format(settings.MEDIA_ROOT)
			for img in os.listdir(folder_temp):
				img_to_remove_path="{}/{}".format(folder_temp,img)
				os.remove(img_to_remove_path)
			return response
			
		else: #presiono el boton de Full download
			invoice_id = 'DOWNLOADPHOTO_{}{}'.format(request.session['lastname'],\
									datetime.now().strftime('%Y%m%d_%H%M%S'))
			pic_paths = []
			amount_free_photos=0
			amount_paid_photos=0
			for key, value in request.POST.items():
				if key != 'pay':
					path , is_free = key.split('_indicador_')
					if int(is_free):
						amount_free_photos+=1
					else:
						amount_paid_photos+=1

					pic_paths.append(path)

			photos_selected=[]
			for key, val in request.POST.items():
				if key != 'pay':
					img_path="{}/{}".format(settings.MEDIA_ROOT,key)
					photos_selected.append(img_path)


			context = {'amount': len(pic_paths),
						'amount_free_photos': amount_free_photos,
						'amount_paid_photos': amount_paid_photos,
						'unit_price': settings.PRICE_P_PHOTO,
						'total_price': (amount_paid_photos*settings.PRICE_P_PHOTO),
						'pics':pic_paths, 
						'invoice_id':invoice_id,
						'photos_selected': photos_selected
						}
			request.session['backend_context'] = context #almaceno el contexto en cache

			return redirect(reverse('payment:process')) #llamo a la view de pago
			
						

	else:
		return redirect('/')


	

download/templates/initial.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
   <link href="{% static 'css/personal/download.css' %}" rel="stylesheet" media="screen">
   <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block content %}
   <!-- Carrusel -->
   {% include 'carrusel.html' %}
   
   <div class="masthead personal-height">
      <div class="container">
         <div class="rowi">
            <div class="col-12 text-center">
               <h1 class="font-styles">Download your photos here !</h1>
               <p class="lead colorlightgray">Select the day of your excursion</p>
               <div class='form'>
                  <form method="post" name="formu" id="form" enctype="multipart/form-data">
                     {% csrf_token %}
                     <input placeholder="Date" type="text" name="daterange" id="fecha" class="datepicker boton"/>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
{% endblock %}


{% block extrajs %}
   <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js">
   </script>

   <script src="{% static 'js/calendardownload.js' %}" type="text/javascript">
   </script>
   
   <script type="text/javascript">
      var available_dates = '{{available_dates}}';
      var start = '{{start}}';
      var end = '{{end}}';
   </script>
{% endblock %}

download/templates/order.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}	
	<link href="{% static 'css/personal/download.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{% block content %}
	<div class="masthead">
	   <div class="container">
	      <div class="rowi">
	         <h1 class="font-styles">Form of {{photo_date}} photos</h1>
	         <h3 class="lead">Please fill in the below form to continue</h3>
	         <div class="jumbotron jumbotron-personal">
	            <form method="post" name="formu" enctype="multipart/form-data" action="{% url 'download:order'%}">
	               {% csrf_token %}
	               {% for field in download_form %}
	               <div class="form-group row">
	                  <label class="col-sm-2">{{field.label_tag}}</label>
	                  <div class="col-sm-10">
	                     {{field}}
	                     {% if field.errors %}
	                     <div class="alert alert-danger danger-cls" role="alert">
	                        {{field.errors.as_text}}
	                     </div>
	                     {% endif %}
	                  </div>
	               </div>
	               {% endfor %}
	               <div>
	                  <input type="submit" value="Next" class="btn btn-primary cls-input"/>
	               </div>
	            </form>
	         </div>
	      </div>
	   </div>
	</div>
{% endblock %}

download/templates/photos.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
   <link href="{% static 'css/personal/download.css' %}" rel="stylesheet" media="screen">
   <link rel="stylesheet" type="text/css" href="{% static 'css/personal/photos.css' %}" />
{% endblock %}

{% block content %}
   <div class="masthead">
      <div class="container">
         <div class="rowi2">
            <div>
               <div>
                  <div class="verticals twelve">
                     <h1 class="font-styles">PHOTOS AVAILABLES FOR {{photo_date}}</h1>
                  </div>
               </div>
               <div class="jumbotron jumbotron-photos">
                  <form method="post" name="formu" enctype="multipart/form-data" action="{% url 'download:photos' %}">
                     <div>
                        <div class="verticals twelve">
                           <ul class="uploaded-pics" >
                              {% for p in photos %}
                              <li>
                                 <!-- El nombre es : IMAGEPATH_indicador_ISFREE para poder atajarlo en el BackEnd-->
                                 <input type="checkbox" id="checkthis{{forloop.counter}}" name="{{p.image}}_indicador_{{p.is_free|yesno:'1,0'}}"/> 
                                 <label for="checkthis{{forloop.counter}}">
                                    {% if p.is_free %}
                                    <div class="isfree animated infinite pulse slower">
                                       <img class="no-pointer" src="{% get_media_prefix %}{{ p.image }}"/>
                                       <span class="label label-default">Free</span>
                                    </div>
                                    {%else%}
                                    <img class="no-pointer" src="{% get_media_prefix %}{{ p.image }}"/>
                                    {%endif%}       
                                 </label>
                              </li>
                              {% endfor %}
                           </ul>
                        </div>
                        <div class="center-downloads-btn">
                           <input name="free" id='free' type="submit" value="Free Download" class="submitbtn"/>
                           <input name="pay" id='pay' type="submit" value="Full Download" class="submitbtn"/>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
      <!-- infoModal -->
      <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
         <div class="modal-dialog" role="document">
            <div class="modal-content">
               <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Download your Pics</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
               </div>
               <div class="modal-body">
                  Below are the photos taken on {{photo_date}}, please select the photos you want to download and select a download method.
                  <br><br>The free method will download the photos with a watermark, except those indicated as free. <br><br>The full method will redirect you to the payment process for the download without watermark.
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-info" data-dismiss="modal">Ok</button>
               </div>
            </div>
         </div>
      </div>
   </div>
{% endblock %}

{% block extrajs %}
   <script src="{% static 'js/photos.js' %}" type="text/javascript"></script>
{% endblock %}