excursion/urls.py
from django.conf.urls import url
from excursion.views import (initial_view, 
							order_view, 
							ajax_query)


urlpatterns = [
    url(r'^$', initial_view, name='initial'),
    url(r'^order$', order_view, name='order'),
    url(r'^ajax$', ajax_query, name='ajax'),

]

home/urls.py
from django.conf.urls import url
from home.views import home_view

urlpatterns = [
    url(r'^$', home_view, name='home_view'),

]

picpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^download/', include('download.urls', namespace='download')),
    url(r'^excursion/', include('excursion.urls', namespace='excursion')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excursion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime, time

from django.db import models

from django.conf import settings

HOUR_CHOICES = [(time(hour=x), '{:02d}:00'.format(x)) for x in range(0, 24)]

class Excursion(models.Model):
	name = models.CharField(max_length=100)
	date = models.DateField()
	turn = models.TimeField(choices=HOUR_CHOICES)
	detail = models.TextField()
	available = models.IntegerField()
	price = models.FloatField()

	def __unicode__(self):
		unicode_str = "{} at {} {}".format(self.name, self.date, self.turn.strftime("%I %p"))
		return unicode_str


class Tourist(models.Model):
	name = models.CharField(max_length=100)
	lastname = models.CharField(max_length=100)
	email = models.EmailField(max_length=100)
	phone = models.CharField(max_length=20)
	amount_people = models.IntegerField()
	hotel = models.CharField(max_length=50)
	comment = models.TextField()
	excursion = models.ForeignKey('Excursion', on_delete=models.CASCADE)

	def __unicode__(self):
		unicode_str = "{} {} {} {} {}".format(self.name, 
											self.lastname, 
											self.email, 
											self.phone, 
											self.excursion
											)
		return unicode_str


class Hotel(models.Model):
	name = models.CharField(max_length=100)


class Reserve(models.Model):
	tourist = models.CharField(max_length=100)



    

excursion/forms.py
from datetime import datetime
from django import forms
from excursion.models import Tourist, Hotel


def set_field_html_name(cls, new_name):
    """
    Cambia el nombre del attr 'name', ya que el objeto forms.Form
    le coloca por default el nombre del campo.
    """
    old_render = cls.widget.render
    def _widget_render_wrapper(name, value, attrs=None):
        return old_render(new_name, value, attrs)

    cls.widget.render = _widget_render_wrapper



class TouristForm(forms.Form):
	name = forms.CharField(
		label = 'Name', 
		max_length=100,
		widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'Enter name...'}
			)
		)
	lastname = forms.CharField(
		label = 'Last Name', 
		max_length=100,
		widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'Enter last name...'}
			)
		)
	email = forms.EmailField(
		max_length=100,
		widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'email@domain.com'}
			)
		)
	phone = forms.CharField(max_length=20, 
		widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'Enter a cellphone number...'}
			)
		)


	excursion = forms.CharField(max_length=100,
		widget=forms.TextInput(attrs={
			'class': 'form-control',
			'readonly':True}
			)
		)

	price = forms.FloatField(
		widget=forms.HiddenInput(),
		)

	hotel = forms.CharField()

	amount_people = forms.IntegerField()

	date = forms.DateField(
		widget=forms.TextInput(attrs={
			'class': 'form-control',
			'placeholder': 'Enter a date...',
			'id': 'fecha'}
			))
	# set_field_html_name(date, 'daterange')#cambiando el valor de 'name'

	turn = forms.CharField()



	comment = forms.CharField(
		label = 'Comments', 
		max_length=300,
		widget=forms.Textarea(attrs={
			'rows':3, 'style':'resize:none',
			'class':'form-control cls-input',
			'placeholder': 'Enter your comment...'})
		)

	def __init__(self, hotels, *args, **kwargs):
		super(TouristForm, self).__init__(*args, **kwargs)
		# self.fields['turn'] = forms.ChoiceField(
		# 	choices=[(turn, turn.strftime('%I:%M %p')) for turn in available_turns]
		# 		)
		if hotels:
			self.fields['hotel'] = forms.ChoiceField(
				choices=hotels)


	def clean_date(self):
		selected_date = self.cleaned_data['date']
		return selected_date.strftime("%Y-%m-%d")

		

excursion/views.py
from __future__ import unicode_literals

import json
from datetime import datetime

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

from django.core.serializers.json import DjangoJSONEncoder

from .models import Excursion, Tourist, Hotel
from .forms import TouristForm


def initial_view(request):
	if request.method == 'POST':
		for k,v in request.POST.items():
			if k != 'csrfmiddlewaretoken':
				excursion_name = k

		qs_available_dates = Excursion.objects\
			.filter(name__iexact=excursion_name)\
			.values_list('date', flat=True).order_by('date')

		available_dates = json.dumps([str(date) for date in qs_available_dates])

		price = Excursion.objects\
					.filter(name__iexact=excursion_name)\
					.values_list('price',flat=True)\
					.distinct()[0]

		form = TouristForm(
			initial={'excursion':excursion_name,'price':price},
			hotels=Hotel.objects.all().values_list('name',flat=True)
			)


		context = {'excursion_name': excursion_name,
					'price': price,
					'available_dates':available_dates,
					'start': qs_available_dates[0].strftime("%d-%m-%Y"),
					'end': qs_available_dates.reverse()[0].strftime("%d-%m-%Y"),
					'form':form
					}
		return render(request, 'form_excursion.html', context)


	else:
		context = {'excursions':[]}
		for i in Excursion.objects.all().distinct().values('name','detail'):
			dateqs, priceqs = [Excursion.objects\
									.filter(name = i['name'])\
									.values_list('date', flat=True)\
									.distinct() , 
							Excursion.objects\
									.filter(name = i['name'])\
									.values_list('price', flat=True)\
									.distinct()[0]
									]

			context['excursions'].append({'name':i['name'],
										   'detail':i['detail'],
										   'date':dateqs,
										   'price':priceqs
										   })


		return render(request, "excursion.html", context)


@csrf_exempt
def order_view(request):
	if request.method == 'POST':

		form = TouristForm(data=request.POST, hotels=None)

		if form.is_valid():
			data = form.cleaned_data
			print(data)

			invoiceid = '{} {} paid:{}'.format(data['excursion'],
										data['lastname'],
										datetime.now().strftime('%Y-%m-%d at %H:%M:%S'))

			excur_obj = Excursion.objects\
				.get(name__iexact=data['excursion'],
					date=data['date'],
					turn=data['turn'])


			contexto = {'excursion_name': data['excursion'],
						'name': data['name'],
						'lastname': data['lastname'],
						'email': data['email'],
						'phone': data['phone'],
						'date':data['date'], 
						'turn':data['turn'],
						'hotel': data['hotel'],
						'amount_people': data['amount_people'],
						'comment': data['comment'],
						'total_to_pay': float(data['price']) * float(data['amount_people']),
						'invoiceid':invoiceid,
						'id_excur': excur_obj.id
						}
			
			request.session['backend_context'] = contexto #almaceno el contexto en cache

			return redirect(reverse('payment:payexcur')) #llamo a la view de pago
		
		else:
			print('no es valido', form.errors)

			excursion_name = request.POST.get('excursion')
			price = request.POST.get('price')
			qs_available_dates = Excursion.objects\
				.filter(name__iexact=excursion_name)\
				.values_list('date', flat=True).order_by('date')

			available_dates = json.dumps([str(date) for date in qs_available_dates])
			form = TouristForm(data=request.POST,
				initial={'excursion':excursion_name,'price':price},
				hotels=Hotel.objects.all().values_list('name',flat=True)
				)

			context = {'excursion_name': excursion_name,
					'price': price,
					'available_dates':available_dates,
					'start': qs_available_dates[0].strftime("%d-%m-%Y"),
					'end': qs_available_dates.reverse()[0].strftime("%d-%m-%Y"),
					'form':form
					}
			return render(request, 'form_excursion.html', context)


	else:
		return redirect('/')





def ajax_query(request):
	
	if request.GET.get('solicitud')=='turn':
		selected_date = request.GET.get('selected_date', None)
		excursion = request.GET.get('excursion', None)
		qs_turns = Excursion.objects\
					.filter(name__iexact=excursion, date=selected_date)\
					.values('turn')\
					.order_by('turn')

		return HttpResponse(json.dumps(list(qs_turns), cls=DjangoJSONEncoder))

	elif request.GET.get('solicitud')=='available':
		selected_date = request.GET.get('selected_date', None)
		excursion = request.GET.get('excursion', None)
		turn = request.GET.get('turn', None)

		qs_available_coupons = Excursion.objects\
						.filter(name__iexact=excursion,
								date=selected_date,
								turn=turn)\
						.values_list('available',flat=True)

		return HttpResponse(json.dumps(qs_available_coupons[0], cls=DjangoJSONEncoder))

excursion/templates/excursion.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}
   <link href="{% static 'css/personal/excursion.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{% block content %}

  <!-- Carrusel -->
  {% include 'carrusel.html' %}
   <div class="masthead">
      <div class="container">
         <div class="rowi">
            <div class="col-12 text-center">
               <div class="row">
                  <form method="post" name="formu" enctype="multipart/form-data" action="{% url 'excursion:initial' %}">
                     {% for excursion in excursions %}
                     {% csrf_token %}
                     <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                           {% with 'images/personal/excursions/'|add:excursion.name|add:'.jpg' as imagePath %}
                              <img src='{% static imagePath %}' />
                           {% endwith %}
                           <div class="caption">
                              <h3>{{excursion.name}}</h3>
                              <p>{{excursion.detail}}</p>
                              <p>
                                 <a id="{{excursion.name|cut:' '|lower}}" class="btn btn-info" role="button" target="moreinfo">
                                 More Info
                                 </a>
                                 <input type="submit" name="{{excursion.name}}" value="Reserve" class="btn btn-primary" role="button"></input>
                              </p>
                           </div>
                        </div>
                     </div>
                     {% endfor %}
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
   {% for excursion in excursions %}
      <!-- MODAL OF {{excursion.name}} -->
      {% with obj=excursion %}
         {% include "information.html" %}
      {% endwith %}
      <!-- END MODAL -->
   {% endfor %}


{% endblock %}


{% block extrajs %}
   <script src="{% static 'js/modalexcursion.js' %}"></script>
{% endblock %}

excursion/templates/form_excursion.html
{% extends 'base.html' %}
{% load static %}


{% block extrahead %} 
   <link href="{% static 'css/personal/excursion.css' %}" rel="stylesheet" media="screen">
   <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}


{% block content %}
   <div class="masthead">
      <div class="container">
         <div class="rowi">
            <h1 class="font-styles">Form of {{excursion_name}} Excursion</h1>
            <h3 class="lead">Please fill in the below form to continue</h3>
            <div class="jumbotron jumbotron-personal">
               <form class="form-horizontal" method="post" name="formu" enctype="multipart/form-data" action="{% url 'excursion:order'%}">
                  <!-- {% csrf_token %} -->
                  {{form.price}} <!-- PRECIO OCULTO, solo lo quiero enviar por POST pero no se debe editar -->
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.name.label_tag}}</label>
                     <div class="col-sm-10">
                        {{form.name}}
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.lastname.label_tag}}</label>
                     <div class="col-sm-10">
                        {{form.lastname}}
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label col-sm-2" for="email">{{form.email.label_tag}}</label>
                     <div class="col-sm-10">
                        {{form.email}}
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.phone.label_tag}}</label>
                     <div class="col-sm-10">
                        {{form.phone}}
                     </div>
                  </div>
                  <hr>
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.excursion.label_tag}}</label>
                     <div class="col-sm-10">
                        {{form.excursion}}
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.date.label_tag}}</label>
                     <div class="col-sm-5">
                        {{form.date}}
                     </div>
                     <div class="form-group">
                        <label class="control-label col-sm-1">{{form.turn.label_tag}}</label>
                        <div class="col-sm-4">
                           <select class="form-control" name='{{form.turn.name}}' id='turn'>
                              <option selected disabled>Choose a turn...</option>
                              {% for key, value in form.fields.turn.choices %}
                              <option value="{{key}}">{{value}}</option>
                              {% endfor %}
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.hotel.label_tag}}</label>
                     <div class="col-sm-5">
                        <select class="form-control" name='{{form.hotel.name}}' id="sel1">
                           <option selected disabled>Choose a hotel...</option>
                           {% for hotel in form.fields.hotel.choices %}
                           <option value="{{hotel}}">{{hotel}}</option>
                           {% endfor %}
                        </select>
                     </div>
                     <div class="col-sm-5">
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                           <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                           <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                     </div>
                     <label class="control-label col-sm-2">Amount of People</label>
                     <div class="col-sm-3">
                        <select class="form-control" id='amount' name='{{form.amount_people.name}}'>
                           <option selected disabled>Amount of People</option>
                        </select>
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label col-sm-2">{{form.comment.label_tag}}</label>
                     <div class="col-sm-10">
                        {{form.comment}}
                     </div>
                  </div>
                  <h4>Total to pay: <span id='totaltopay'>$ {{price|floatformat}}</span></h4>
                  <button type="submit" class="btn btn-primary">
                  <i class="fa fa-calendar" aria-hidden="true"></i>
                  Reserve now
                  </button>
               </form>
            </div>
         </div>
      </div>
   </div>
{% endblock %}



{% block extrajs %}
   <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
   <script src="{% static 'js/calendarexcursion.js' %}" type="text/javascript"></script>
   <script type="text/javascript">
      var available_dates = '{{available_dates}}';
      var start = '{{start}}';
      var end = '{{end}}';
      var price = '{{price}}';
      
      $('#centralModalInfo').modal('show');
      
   </script>
{% endblock %}

excursion/templates/information.html
{% load static %}

<div class="modal fade" id="{{excursion.name|cut:' '|lower}}modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-notify modal-info" role="document">
      <div class="modal-content" style="margin: 30% auto;">
         <div class="modal-header">
            <p class="heading lead">Details of {{excursion.name}} Excursion</p>
         </div>
         <div class="modal-body">
            <div class="text-center thumbnail">
               {% with 'images/personal/excursions/'|add:excursion.name|add:'.jpg' as imagePath %}
                  <img src='{% static imagePath %}' />
               {% endwith %}
            </div>
            <div class="text-center">
               <p><strong>Excursion Name:</strong> {{excursion.name}}</p>
               <p><strong>Details:</strong> {{excursion.detail}}</p>
               <p><strong>Available dates:<br></strong>
                  {% for d in excursion.date %}
                     {{d|date:"d-M-Y"}}
                  <br>
                  {% endfor %}
               </p>
               <p><strong>Precio:</strong> ${{excursion.price}}</p>
            </div>
         </div>
         <div class="modal-footer justify-content-center">
            <a type="button" class="btn btn-primary" data-dismiss="modal">
            <span>OK</span>
            </a>
         </div>
      </div>
   </div>
</div>