download/urls.py
from django.conf.urls import url
from download.views import (initial_view, 
							order_view,
							photos_view,)


urlpatterns = [
    url(r'^$', initial_view, name='initial'),
    url(r'^order/$', order_view, name='order'),
    url(r'^photos/$', photos_view, name='photos'),

]

home/urls.py
from django.conf.urls import url
from home.views import home_view

urlpatterns = [
    url(r'^$', home_view, name='home_view'),

]

picpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^download/', include('download.urls', namespace='download')),
    url(r'^excursion/', include('excursion.urls', namespace='excursion')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% include 'head.html' %}
	{% block extrahead %}{% endblock %}
</head>
<body>
	  <!-- Navigation -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle nav</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- Logo text or image -->

        <a class="navbar-brand" href="{% url 'home:home_view' %}">
        </a>

      </div>
      <div class="navigation collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li class="current">
            <!-- <a href="{% url 'home:home_view' %}">Home</a></li> -->
          <li>
            <div class="dropdown">
              <button class="dropdown-toggle dropdown-services" type="button" data-toggle="dropdown">Services
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="{% url 'home:home_view' %}#services">Services</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'excursion:initial' %}">Excursions</a></li>
                <li><a href="{% url 'download:initial' %}">Download Photos</a></li>
                <li><a href="#">Photo sessions</a></li>
              </ul>
            </div>  
          </li>
          <li><a href="{% url 'home:home_view' %}#about">About</a></li>
          <li><a href="{% url 'home:home_view' %}#portfolio">Works</a></li>
          <li><a href="{% url 'home:home_view' %}#team">Team</a></li>
          <li><a href="{% url 'home:home_view' %}#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

  {% include 'footer.html' %}
	
	{% include 'javascript.html' %}
	{% block extrajs %}{% endblock %}
</body>
</html>

templates/carrusel.html
  {% load static %}
  
  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel slide carousel-fade" data-ride="carousel">

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="item active">
            <div class="carousel-background">
              <img src="{%static 'images/personal/home/carousel/carousel2.jpg'%}" alt="">
            </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown">Alstar web studio</h2>
                <p class="animated fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animated fadeInUp">Read More</a>
              </div>
            </div>
          </div>
          
          <!-- Slide 2 -->
          <div class="item">
            <div class="carousel-background">
              <img src="{%static 'images/personal/home/carousel/carousel3.jpg'%}" alt="">
            </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown">Creativity and technology</span></h2>
                <p class="animated fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animated fadeInUp">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="item">
            <div class="carousel-background">
              <img src="{%static 'images/personal/home/carousel/carousel1.jpg'%}" alt="">
            </div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animated fadeInDown">Sequi ea ut et est quaerat</span></h2>
                <p class="animated fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animated fadeInUp">Read More</a>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon fa fa-angle-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon fa fa-angle-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
  </section><!-- #intro -->

templates/footer.html
{% load static %}

<!-- Contact -->
<section id="contact" class="home-section-contact bg-white4">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <div class="section-heading">
          <h2 class="colordarkgray">Contact us</h2>
          <div class="heading-line"></div>
          <p class="colordarkgray">If you have any question or just want to say 'hello' to Alstar web studio please fill out form below and
            we will be get in touch with you within 24 hours. </p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <div id="sendmessage">Your message has been sent. Thank you!</div>
        <div id="errormessage"></div>

        <form action="" method="post" class="form-horizontal contactForm" role="form">
          <div class="col-md-offset-2 col-md-8">
            <div class="form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4"
                data-msg="Please enter at least 4 chars" />
              <div class="validation"></div>
            </div>
          </div>

          <div class="col-md-offset-2 col-md-8">
            <div class="form-group">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email"
                data-msg="Please enter a valid email" />
              <div class="validation"></div>
            </div>
          </div>

          <div class="col-md-offset-2 col-md-8">
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4"
                data-msg="Please enter at least 8 chars of subject" />
              <div class="validation"></div>
            </div>
          </div>

          <div class="col-md-offset-2 col-md-8">
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us"
                placeholder="Message"></textarea>
              <div class="validation"></div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
              <button type="submit" class="btn btn-theme btn-lg btn-block">Send message</button>
            </div>
          </div>
        </form>

      </div>
    </div>

  </div>
</section>

<!-- Bottom widget -->
<section id="bottom-widget" class="home-section bg-white5">
  <div class="container"
    <div class="row">
      <div class="col-md-4">
        <div class="contact-widget wow bounceInLeft">
          <i class="fa fa-map-marker fa-4x"></i>
          <h5 class="colorwhitegray">Main Office</h5>
          <p class='colorwhitegray'>
            109 Borough High Street,<br />London SE1 1NL
          </p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="contact-widget wow bounceInUp">
          <i class="fa fa-phone fa-4x"></i>
          <h5 class="colorwhitegray">Call</h5>
          <p class='colorwhitegray'>
            +1 111 9998 7774<br> +1 245 4544 6855

          </p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="contact-widget wow bounceInRight">
          <i class="fa fa-envelope fa-4x"></i>
          <h5 class="colorwhitegray">Email us</h5>
          <p class='colorwhitegray'>
            hello@alstarstudio.com<br />sales@alstarstudio.com
          </p>
        </div>
      </div>
    </div>
    
  </div>
  </section>

  
<div class="row mar-top30">
        <div class="col-md-12">
          <h5 class="colorwhitegray">We're on social networks</h5>
          <ul class="social-network">
            <li><a href="#">
                <span class="fa-stack fa-2x">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook fa-stack-1x fa-backcolor"></i>
                </span></a>
            </li>
            <li><a href="#">
                <span class="fa-stack fa-2x">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-dribbble fa-stack-1x fa-backcolor"></i>
                </span></a>
            </li>
            <li><a href="#">
                <span class="fa-stack fa-2x">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-backcolor"></i>
                </span></a>
            </li>
            <li><a href="#">
                <span class="fa-stack fa-2x">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-pinterest fa-stack-1x fa-backcolor"></i>
                </span></a>
              </li>
            </ul>
          </div>
        </div>
<!-- wavesssssssssssss  -->

    <div class='body-waves'>
        <div class="wrap">
                <svg class = 'svg-waves' id="waves" viewBox="0 300 1080 330">0 345 1080 300
                <path id="layer-12" class="st0" d="M1417.2,811.3H-9.6V385.7l76.8-35.4c0,0,20.7,35.4,78,35.4s95.1-35.4,95.1-35.4
                    s13.4,35.4,63.4,35.4s87.8-35.4,87.8-35.4s24.4,35.4,73.2,35.4s69.5-35.4,69.5-35.4s30.5,35.4,86.6,35.4c56.1,0,82.9-35.4,82.9-35.4
                    s22,35.4,63.4,35.4s80.5-35.4,80.5-35.4s23.2,35.4,72,35.4s75.6-35.4,75.6-35.4s20.7,35.4,63.4,35.4c42.7,0,73.2-35.4,73.2-35.4
                    s26.8,35.4,63.4,35.4c36.6,0,65.9-35.4,65.9-35.4s41.5,35.4,76.8,35.4s79.3-35.4,79.3-35.4V811.3z"/>
                <path id="layer-11" class="st1" d="M-80.6,829.5h1426.8V403.9l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4c-50,0-87.8-35.4-87.8-35.4s-24.4,35.4-73.2,35.4s-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4c-41.5,0-80.5-35.4-80.5-35.4s-23.2,35.4-72,35.4s-75.6-35.4-75.6-35.4
                    s-20.7,35.4-63.4,35.4s-73.2-35.4-73.2-35.4s-26.8,35.4-63.4,35.4s-65.9-35.4-65.9-35.4S34,403.9-1.3,403.9s-79.3-35.4-79.3-35.4
                    V829.5z"/>
                <path id="layer-10" class="st2" d="M-24.5,852h1426.8V426.3l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4c-50,0-87.8-35.4-87.8-35.4s-24.4,35.4-73.2,35.4c-48.8,0-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4S545,391,545,391s-23.2,35.4-72,35.4S397.4,391,397.4,391s-20.7,35.4-63.4,35.4
                    S260.9,391,260.9,391s-26.8,35.4-63.4,35.4S131.6,391,131.6,391s-41.5,35.4-76.8,35.4S-24.5,391-24.5,391V852z"/>
                <path id="layer-9" class="st3" d="M-80.6,878.3h1426.8V452.7l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4c-50,0-87.8-35.4-87.8-35.4s-24.4,35.4-73.2,35.4s-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4c-41.5,0-80.5-35.4-80.5-35.4s-23.2,35.4-72,35.4s-75.6-35.4-75.6-35.4
                    s-20.7,35.4-63.4,35.4s-73.2-35.4-73.2-35.4s-26.8,35.4-63.4,35.4s-65.9-35.4-65.9-35.4S34,452.7-1.3,452.7s-79.3-35.4-79.3-35.4
                    V878.3z"/>
                <path id="layer-8" class="st0" d="M1388.9,894H-37.9V468.4L38.9,433c0,0,20.7,35.4,78,35.4s95.1-35.4,95.1-35.4s13.4,35.4,63.4,35.4
                    s87.8-35.4,87.8-35.4s24.4,35.4,73.2,35.4S506,433,506,433s30.5,35.4,86.6,35.4c56.1,0,82.9-35.4,82.9-35.4s22,35.4,63.4,35.4
                    s80.5-35.4,80.5-35.4s23.2,35.4,72,35.4S967,433,967,433s20.7,35.4,63.4,35.4s73.2-35.4,73.2-35.4s26.8,35.4,63.4,35.4
                    s65.9-35.4,65.9-35.4s41.5,35.4,76.8,35.4c35.4,0,79.3-35.4,79.3-35.4V894z"/>
                <path id="layer-7" class="st1" d="M-108.9,912.2h1426.8V486.6l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4s-87.8-35.4-87.8-35.4s-24.4,35.4-73.2,35.4c-48.8,0-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4s-80.5-35.4-80.5-35.4s-23.2,35.4-72,35.4S313,451.2,313,451.2
                    s-20.7,35.4-63.4,35.4s-73.2-35.4-73.2-35.4s-26.8,35.4-63.4,35.4s-65.9-35.4-65.9-35.4s-41.5,35.4-76.8,35.4s-79.3-35.4-79.3-35.4
                    V912.2z"/>
                <path id="layer-6" class="st2" d="M-52.8,934.7H1374V509.1l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4c-50,0-87.8-35.4-87.8-35.4s-24.4,35.4-73.2,35.4c-48.8,0-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4c-41.5,0-80.5-35.4-80.5-35.4s-23.2,35.4-72,35.4s-75.6-35.4-75.6-35.4
                    s-20.7,35.4-63.4,35.4s-73.2-35.4-73.2-35.4s-26.8,35.4-63.4,35.4s-65.9-35.4-65.9-35.4s-41.5,35.4-76.8,35.4s-79.3-35.4-79.3-35.4
                    V934.7z"/>
                <path id="layer-5" class="st3" d="M-108.9,961h1426.8V535.4l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4S916.7,500,916.7,500s-24.4,35.4-73.2,35.4c-48.8,0-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4S460.6,500,460.6,500s-23.2,35.4-72,35.4S313,500,313,500s-20.7,35.4-63.4,35.4
                    S176.5,500,176.5,500s-26.8,35.4-63.4,35.4S47.2,500,47.2,500s-41.5,35.4-76.8,35.4s-79.3-35.4-79.3-35.4V961z"/>
                <path id="layer-4" class="st0" d="M-40.8,972.4h1426.8V546.8l-76.8-35.4c0,0-20.7,35.4-78,35.4s-95.1-35.4-95.1-35.4
                    s-13.4,35.4-63.4,35.4c-50,0-87.8-35.4-87.8-35.4s-24.4,35.4-73.2,35.4s-69.5-35.4-69.5-35.4s-30.5,35.4-86.6,35.4
                    c-56.1,0-82.9-35.4-82.9-35.4s-22,35.4-63.4,35.4c-41.5,0-80.5-35.4-80.5-35.4s-23.2,35.4-72,35.4s-75.6-35.4-75.6-35.4
                    s-20.7,35.4-63.4,35.4s-73.2-35.4-73.2-35.4s-26.8,35.4-63.4,35.4s-65.9-35.4-65.9-35.4s-41.5,35.4-76.8,35.4s-79.3-35.4-79.3-35.4
                    V972.4z"/>
                <path id="layer-3" class="st1" d="M1457.1,990.6H30.2V565l76.8-35.4c0,0,20.7,35.4,78,35.4s95.1-35.4,95.1-35.4s13.4,35.4,63.4,35.4
                    s87.8-35.4,87.8-35.4s24.4,35.4,73.2,35.4s69.5-35.4,69.5-35.4s30.5,35.4,86.6,35.4s82.9-35.4,82.9-35.4s22,35.4,63.4,35.4
                    s80.5-35.4,80.5-35.4s23.2,35.4,72,35.4s75.6-35.4,75.6-35.4s20.7,35.4,63.4,35.4c42.7,0,73.2-35.4,73.2-35.4s26.8,35.4,63.4,35.4
                    c36.6,0,65.9-35.4,65.9-35.4s41.5,35.4,76.8,35.4c35.4,0,79.3-35.4,79.3-35.4V990.6z"/>
                <path id="layer-2" class="st2" d="M1362,1013.1H-64.9V587.5L12,552.1c0,0,20.7,35.4,78,35.4s95.1-35.4,95.1-35.4
                    s13.4,35.4,63.4,35.4s87.8-35.4,87.8-35.4s24.4,35.4,73.2,35.4s69.5-35.4,69.5-35.4s30.5,35.4,86.6,35.4s82.9-35.4,82.9-35.4
                    s22,35.4,63.4,35.4s80.5-35.4,80.5-35.4s23.2,35.4,72,35.4s75.6-35.4,75.6-35.4s20.7,35.4,63.4,35.4c42.7,0,73.2-35.4,73.2-35.4
                    s26.8,35.4,63.4,35.4c36.6,0,65.9-35.4,65.9-35.4s41.5,35.4,76.8,35.4c35.4,0,79.3-35.4,79.3-35.4V1013.1z"/>
                <path id="layer-1" class="st3" d="M1394.9,1041.8H-32V616.1l76.8-35.4c0,0,20.7,35.4,78,35.4s95.1-35.4,95.1-35.4
                    s13.4,35.4,63.4,35.4s87.8-35.4,87.8-35.4s24.4,35.4,73.2,35.4s69.5-35.4,69.5-35.4s30.5,35.4,86.6,35.4c56.1,0,82.9-35.4,82.9-35.4
                    s22,35.4,63.4,35.4s80.5-35.4,80.5-35.4s23.2,35.4,72,35.4c48.8,0,75.6-35.4,75.6-35.4s20.7,35.4,63.4,35.4s73.2-35.4,73.2-35.4
                    s26.8,35.4,63.4,35.4s65.9-35.4,65.9-35.4s41.5,35.4,76.8,35.4s79.3-35.4,79.3-35.4V1041.8z"/>
                </svg></div>
                
                
               
</div>
  <!-- ************************************************************************************  -->
  



  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>Copyright &copy; Company. All rights reserved.</p>
      
        </div>
      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

templates/head.html
{% load static %}
<link rel="icon" href="{% static 'images/personal/favicon.png' %}">
<title>My Tailor Tours</title>
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<!-- css -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400,300,700,800" rel="stylesheet" media="screen">

<link href="{% static 'css/template/bootstrap.min.css' %}" rel="stylesheet" media="screen">
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>


<link href="{% static 'css/template/style.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/template/default.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/personal/homemods.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/personal/home.css' %}" rel="stylesheet" media="screen">

<link href="{% static 'css/personal/waves.css' %}" rel="stylesheet" media="screen">

templates/javascript.html
{% load static %}
<!-- js -->
<script src="{% static 'js/template/jquery.js' %}"></script>
<script src="{% static 'js/template/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js">
</script>

<script src="{% static 'js/template/wow.min.js' %}"></script>
<script src="{% static 'js/template/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'js/template/jquery.nav.js' %}"></script>
<script src="{% static 'js/template/modernizr.custom.js' %}"></script>
<script src="{% static 'js/template/grid.js' %}"></script>
<script src="{% static 'js/template/stellar.js' %}"></script>
<script src="{% static 'js/template/custom.js' %}"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.3.0/snap.svg-min.js"></script>
<script type="text/javascript" src="{% static 'js/waves.js' %}"></script>

<!-------------------------->